### ISSUE TITLE
DATETIME not being tokenized/grouped

### ISSUE THREAD

**Issue by smaili** [atom/language-sql#19]
![datetime](https://cloud.githubusercontent.com/assets/4451986/9199378/ead0be72-3ff6-11e5-8ec0-6b275a170c92.png)

**Comment by 50Wliu** [comment]
@smaili What do you think it should be tokenized as?

**Comment by smaili** [comment]
`storage type sql`

**Comment by 50Wliu** [comment]
I can't reproduce this using Atom 1.3.0-dev-69dfdd0 - can you try again on at least v1.1.0 @smaili?  Thanks.

**Comment by smaili** [comment]
@50Wliu Still not tokenizing in 1.1.0.

**Comment by 50Wliu** [comment]
Ah hah-looks like Atom is still using v0.17.0 of language-sql on 1.1.0 (https://github.com/atom/atom/blob/stable/package.json#L143), while `datetime` was added in v0.18.0.  Sorry!  As a workaround you can try using 1.2.0-beta0.

**Comment by smaili** [comment]
Good catch :+1:
