### ISSUE TITLE
Temp Table Designation Not Highlighted Correctly

### ISSUE THREAD

**Issue by digital-dharma** [atom/language-sql#27]
To designate temp tables in SQL, they are proceeded with a '#' or '##'.  Unfortunately, this seems to highlight them as comments, which is incorrect.
```sql
#MyTempTable
##MySecondTempTable
```

**Comment by DavidLGoldberg** [comment]
Yup, pretty funny.

Sublime has this issue too.

**Comment by gontadu** [comment]
Easy fix from what I have tried (with my limited knowledge) - will send in a PR

**Comment by 50Wliu** [comment]
Fixed by #16.

**Comment by digital-dharma** [comment]
Great work - I'll pull the atom package when available!
