### ISSUE TITLE
Create additional grammars for catering for the various variants

### ISSUE THREAD

**Issue by gontadu** [atom/language-sql#40]
It appears that there is enough differentiation between SQL variants such as T-SQL from Microsoft and the MySQL stuff for instance.

As there is functionality for multiple grammars e.g. how c and c++ are catered for by one package.

Would it make sense to add new grammars to this package then.
There are two forks currently for each of the languages:
MySQL: https://atom.io/packages/language-sql-mysql by @typester
T-SQL: https://atom.io/packages/language-tsql by @mattiascibien 

Perhaps it would be helpful so that we avoid issues like #28 and we could invite the original developers of this package to make those changes?

**Comment by mattiascibien** [comment]
I think this is a better idea than having different packages as it will centralize the development.

**Comment by 50Wliu** [comment]
Do MySQL and T-SQL have different file extensions, or do they share the same ones as SQL?

**Comment by mattiascibien** [comment]
@50Wliu as far as I know i guess they have the same extension.

**Comment by 50Wliu** [comment]
Then combining the grammars into one repository won't be possible until there is intelligent language detection.

**Comment by gontadu** [comment]
In the meantime, is it possible to group all the mysql exclusive keywords into a different colour/capture?
That way it stays in the code but not in the same colour as the popular common SQL keywords like SELECT, etc.

**Comment by 50Wliu** [comment]
Yes, that can be done.  The root scope could be changed from `.sql` to `.mysql`.
